### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vmbrasseur** [tungstenfabric/docs#1]
What's the licensing of the docs in this repository? It doesn't appear that one is applied, but I may be missing something…?

**Comment by pcarver** [comment]
Per the charter https://tungsten.io/wp-content/uploads/2018/03/Tungsten-Fabric-Project-Technical-Charter-3-13-2018-Final.pdf

> Documentation will be received and made available by the Project under the Creative
Commons Attribution 4.0 International License (available at
http://creativecommons.org/licenses/by/4.0/).

but I guess there does need to be a license file in the repo specifically stating that.
