### ISSUE TITLE
[TFB-1523] RTD link to Community Governance Document is broken

### ISSUE THREAD

**Issue by pono** [tungstenfabric/docs#17]
There's a link to the Community Governance Document on the Governance page (http://docs.tungsten.io/en/latest/governance/index.html)  http://docs.tungsten.io/en/latest/governance/index.html This link is broken and goes to the RTD 404 page.

**Comment by pono** [comment]
I was looking at the Governance Overview today (http://docs.tungsten.io/en/latest/governance/index.html) and noticed that all of the links to the governance doc there are also 404ing.

Make sure to check these links when fixing this to ensure they're also working before closing the issue.

**Comment by pono** [comment]
Thanks for catching this. Just ran into this as well. Also, found another broken link to add to this (below). I'm going to remove this reference for the time being to submit a patch. I'll try to address the below and the 404's next week.

Warning, treated as error:

/Users/dhirotsu/git/test/docs/governance/tungsten-fabric-community-governance.rst.rst:380:broken link: https://docs.google.com/document/d/1xFNNPNb8lXXha24lNbKkMMCvE30ydS97Obb1YhEaPeU/edit?usp=sharing (410 Client Error: Gone for url: https://docs.google.com/document/d/1xFNNPNb8lXXha24lNbKkMMCvE30ydS97Obb1YhEaPeU/edit?usp=sharing)

**Comment by SzymonV** [comment]
Fixed

**Comment by SzymonV** [comment]
@pono This issue can be closed now. I don't have permissions to do that.
